<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <IsPackable>false</IsPackable>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CodEaisy.TinySaas.AspNetCore\CodEaisy.TinySaas.AspNetCore.csproj" />
  </ItemGroup>

</Project>
