<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="7.0.20" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="7.0.20" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TinySaasWebApi\TinySaasWebApi.csproj" />
    <ProjectReference Include="..\DefaultWebApi\DefaultWebApi.csproj" />
  </ItemGroup>

</Project>
