name: Test and Analyze

on:
  push:
    branches: [ dev, main]
  pull_request:
    branches: [ dev, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install NBGV
      run: dotnet tool install -g nbgv
    - name: Install dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build src --configuration Release --no-restore
    - name: Test
      run: make test
    - name: Install SonarScanner
      run: dotnet tool install -g dotnet-sonarscanner
    - name: Analyze PR
      if: ${{ github.event_name == 'pull_request' }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        CHANGE_ID: ${{ github.event.pull_request.number }}
      run: make analyze_pr
    - name: Analyze BR
      if: ${{ github.event_name == 'push' }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: make analyze_br
